# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e31bc538fe0c6d8c8018dbfa323cdb73948604160701dc2706c56ef7e0602658fdf661acbe4651b8acf12610cdea973213b51e872df47c0b0eff996c2d20bac

test:
  secret_key_base: 06a6a6b0fff24b629e05569ae0c1c195722297cb65bb9a1e366fc0ee72a6203a7c03f5d663603cf87fa3074794db0f5fac39b00d629f64e1e1b7565b437df77a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
